export const EventName = {
  GAME_START: 'GAME_START',
  GAME_RESET: 'GAME_RESET',
  GAME_OVER: 'GAME_OVER',
  GAME_INIT: 'GAME_INIT',
  /** 金币更新 */
  GOLD_UPDATE: 'GOLD_UPDATE',
  /** 在线奖励更新 */
  ONLINE_REWARD_UPDATE: 'ONLINE_REWARD_UPDATE',
  FIGHT_GOLD_UPDATE: 'FIGHT_GOLD_UPDATE',
  /** 各方战力更新 */
  FIGHT_POWER_UPDATE: 'FIGHT_POWER_UPDATE',
} as const;
